version: 2
updates: 
  - 
    directory: "/"
    milestone: 2
    package-ecosystem: "npm"
    schedule: 
      interval: "daily"
    target-branch: "dependabotprs"
    ignore:
      - dependency-name: "node-fetch"
        update-types: ["version-update:semver-major"]

