name: staging env build and deploy

on:
  push:
    branches:
      - staging

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build 11ty
        uses: cagov/actions-eleventy@master
        with:
          build_task: build:staging 
          build_eleventy_args: --formats=html,njk --input=./pages --output=d./docs
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_GROUND_0C34D501E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig	
          app_location: "/docs" # App source code path	
          api_location: "api" # Api source code path - optional	
          app_artifact_location: "" # Built app content directory - optional	
          ###### End of Repository/Build Configurations ######	